development:
  mailgun:
    authentication: "plain"
    address: "smtp.mailgun.org"
    port: 587
    domain: "mail.mydomain.com"
    user_name: "no-reply@mail.mydomain.com"
    password: "my_password_123"
